In [237]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [238]:
games = pd.read_csv("vgsalesGlobale.csv",index_col="Name") # name veri setinin indexi oldu

In [239]:
games.head(10)

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Wii Sports,1,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
Super Mario Bros.,2,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
Mario Kart Wii,3,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
Wii Sports Resort,4,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
Pokemon Red/Pokemon Blue,5,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
Tetris,6,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
New Super Mario Bros.,7,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
Wii Play,8,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
New Super Mario Bros. Wii,9,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
Duck Hunt,10,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [240]:
# tek bir sütundan olusan veri yapısına series denir excel gibi tablo seklinde olan da dataframe

In [241]:
games.tail(10) # sondan 10 elemana bakar

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Mega Brain Boost,16591,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shirube Kareru,16592,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
Eiyuu Densetsu: Sora no Kiseki Material Collection Portable,16593,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
Myst IV: Revelation,16594,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
Plushees,16595,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
Woody Woodpecker in Crazy Castle 5,16596,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
Men in Black II: Alien Escape,16597,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
SCORE International Baja 1000: The Official Game,16598,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
Know How 2,16599,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
Spirits & Spells,16600,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

In [242]:
games.shape

(16598, 10)

In [243]:
games.dtypes

Rank              int64
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [244]:
# csv dosyasını excele donusturdugumuzde float 64 olan bazı degerler int e donustu sebep??

In [245]:
games.iloc[299] # 300.satiri basiyoruz

Rank                           300
Platform                       PS3
Year                        2008.0
Genre                 Role-Playing
Publisher       Bethesda Softworks
NA_Sales                      2.15
EU_Sales                       1.2
JP_Sales                      0.07
Other_Sales                   0.59
Global_Sales                  4.01
Name: Fallout 3, dtype: object

In [246]:
games.loc["Super Mario Bros."]

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Super Mario Bros.,2,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
Super Mario Bros.,201,GB,1999.0,Platform,Nintendo,3.40,1.30,0.15,0.22,5.07

In [247]:
games.loc["Super Mario Bros.","Rank"]

Name
Super Mario Bros.      2
Super Mario Bros.    201
Name: Rank, dtype: int64

In [248]:
games.loc["Super Mario Bros.","Genre"]

Name
Super Mario Bros.    Platform
Super Mario Bros.    Platform
Name: Genre, dtype: object

In [249]:
games.sort_values(by = "Year")

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Checkers,6898,2600,1980.0,Misc,Atari,0.22,0.01,0.0,0.00,0.24
Boxing,2671,2600,1980.0,Fighting,Activision,0.72,0.04,0.0,0.01,0.77
Freeway,5368,2600,1980.0,Action,Activision,0.32,0.02,0.0,0.00,0.34
Defender,1971,2600,1980.0,Misc,Atari,0.99,0.05,0.0,0.01,1.05
Kaboom!,1768,2600,1980.0,Misc,Activision,1.07,0.07,0.0,0.01,1.15
...,...,...,...,...,...,...,...,...,...,...
Freaky Flyers,16310,GC,NaN,Racing,Unknown,0.01,0.00,0.0,0.00,0.01
Inversion,16330,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.0,0.00,0.01
Hakuouki: Shinsengumi Kitan,16369,PS3,NaN,Adventure,Unknown,0.01,0.00,0.0,0.00,0.01
Virtua Quest,16430,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.0,0.00,0.01
The Smurfs,16496,3DS,NaN,Action,Unknown,0.00,0.01,0.0,0.00,0.01

In [250]:
games.sort_values(by = "Year",ascending=False)

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Imagine: Makeup Artist,5959,DS,2020.0,Simulation,Ubisoft,0.27,0.00,0.00,0.02,0.29
Phantasy Star Online 2 Episode 4: Deluxe Package,14393,PS4,2017.0,Role-Playing,Sega,0.00,0.00,0.03,0.00,0.03
Phantasy Star Online 2 Episode 4: Deluxe Package,16244,PSV,2017.0,Role-Playing,Sega,0.00,0.00,0.01,0.00,0.01
Brothers Conflict: Precious Baby,16441,PSV,2017.0,Action,Idea Factory,0.00,0.00,0.01,0.00,0.01
Shin Megami Tensei IV: Final,8295,3DS,2016.0,Role-Playing,Deep Silver,0.03,0.00,0.14,0.00,0.17
...,...,...,...,...,...,...,...,...,...,...
Freaky Flyers,16310,GC,NaN,Racing,Unknown,0.01,0.00,0.00,0.00,0.01
Inversion,16330,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01
Hakuouki: Shinsengumi Kitan,16369,PS3,NaN,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01
Virtua Quest,16430,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
The Smurfs,16496,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01

In [251]:
games.sort_values(by = ["Year","Genre"],ascending=False).head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Imagine: Makeup Artist,5959,DS,2020.0,Simulation,Ubisoft,0.27,0.0,0.00,0.02,0.29
Phantasy Star Online 2 Episode 4: Deluxe Package,14393,PS4,2017.0,Role-Playing,Sega,0.00,0.0,0.03,0.00,0.03
Phantasy Star Online 2 Episode 4: Deluxe Package,16244,PSV,2017.0,Role-Playing,Sega,0.00,0.0,0.01,0.00,0.01
Brothers Conflict: Precious Baby,16441,PSV,2017.0,Action,Idea Factory,0.00,0.0,0.01,0.00,0.01
XCOM 2,7566,PC,2016.0,Strategy,Take-Two Interactive,0.09,0.1,0.00,0.02,0.20

In [252]:
games.loc["Super Mario Bros.",["Genre","Year","Platform"]]

                      Genre    Year Platform
Name
Super Mario Bros.  Platform  1985.0      NES
Super Mario Bros.  Platform  1999.0       GB

In [253]:
games["Publisher"].head() #  bu bir seriestir

Name
Wii Sports                  Nintendo
Super Mario Bros.           Nintendo
Mario Kart Wii              Nintendo
Wii Sports Resort           Nintendo
Pokemon Red/Pokemon Blue    Nintendo
Name: Publisher, dtype: object

In [254]:
games["Year"].head()

Name
Wii Sports                  2006.0
Super Mario Bros.           1985.0
Mario Kart Wii              2008.0
Wii Sports Resort           2009.0
Pokemon Red/Pokemon Blue    1996.0
Name: Year, dtype: float64

In [255]:
games[games["Genre"] == "Action"].head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Grand Theft Auto V,17,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
Grand Theft Auto: San Andreas,18,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
Grand Theft Auto V,24,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
Grand Theft Auto: Vice City,25,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
Grand Theft Auto III,39,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10

In [256]:
(games["Genre"] == "Action").dtypes

dtype('bool')

In [257]:
games_in_2010 = games["Year"]==2010

In [258]:
games[games_in_2010].head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Kinect Adventures!,16,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
Pokemon Black/Pokemon White,27,DS,2010.0,Role-Playing,Nintendo,5.57,3.28,5.65,0.82,15.32
Call of Duty: Black Ops,32,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
Call of Duty: Black Ops,41,PS3,2010.0,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
Gran Turismo 5,55,PS3,2010.0,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77

In [259]:
games_action = games["Genre"] == "Action"

In [260]:
games[games_in_2010 & games_action].head() # 2010 yılı Action turundeki oyunlar

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Red Dead Redemption,124,PS3,2010.0,Action,Take-Two Interactive,2.79,2.61,0.17,1.03,6.60
Red Dead Redemption,135,X360,2010.0,Action,Take-Two Interactive,3.70,1.97,0.09,0.57,6.34
God of War III,217,PS3,2010.0,Action,Sony Computer Entertainment,2.74,1.36,0.12,0.63,4.84
Assassin's Creed: Brotherhood,374,X360,2010.0,Action,Ubisoft,2.84,0.39,0.03,0.24,3.50
Assassin's Creed: Brotherhood,515,PS3,2010.0,Action,Ubisoft,1.87,0.57,0.11,0.30,2.84

In [261]:
games[games_in_2010 | games_action].head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Kinect Adventures!,16,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
Grand Theft Auto V,17,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
Grand Theft Auto: San Andreas,18,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
Grand Theft Auto V,24,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
Grand Theft Auto: Vice City,25,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15

In [262]:
""" & = ve  |=veya """

' & = ve  |=veya '

In [263]:
after_2015 = games[games["Year"]>2015]

In [264]:
after_2015.head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
FIFA 17,222,PS4,2016.0,Sports,Electronic Arts,0.28,3.75,0.06,0.69,4.77
Uncharted 4: A Thief's End,272,PS4,2016.0,Shooter,Sony Computer Entertainment,1.30,2.07,0.18,0.65,4.20
Tom Clancy's The Division,352,PS4,2016.0,Shooter,Ubisoft,1.28,1.61,0.15,0.57,3.61
Far Cry: Primal,772,PS4,2016.0,Action,Ubisoft,0.59,1.16,0.06,0.33,2.13
Tom Clancy's The Division,847,XOne,2016.0,Shooter,Ubisoft,1.20,0.62,0.00,0.18,2.01

In [265]:
mid_2000 = games[games["Year"].between(2000,2010)]

In [266]:
mid_2000

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Wii Sports,1,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
Mario Kart Wii,3,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
Wii Sports Resort,4,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
New Super Mario Bros.,7,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
Wii Play,8,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
...,...,...,...,...,...,...,...,...,...,...
Woody Woodpecker in Crazy Castle 5,16596,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
Men in Black II: Alien Escape,16597,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
SCORE International Baja 1000: The Official Game,16598,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
Know How 2,16599,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
Spirits & Spells,16600,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [267]:
sport_in_title = games.index.str.lower().str.contains("sport")

In [268]:
games[sport_in_title] # icinde sport gecen oyunlar

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Wii Sports,1,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
Wii Sports Resort,4,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
Kinect Sports,140,X360,2010.0,Sports,Microsoft Game Studios,3.92,1.78,0.03,0.51,6.24
Forza Motorsport 3,161,X360,2009.0,Racing,Microsoft Game Studios,2.99,1.92,0.10,0.51,5.51
Forza Motorsport 4,229,X360,2011.0,Racing,Microsoft Game Studios,2.08,2.04,0.06,0.47,4.64
...,...,...,...,...,...,...,...,...,...,...
Disney Sports Football,15664,GC,2002.0,Sports,Konami Digital Entertainment,0.01,0.00,0.00,0.00,0.02
Winter Sports 3: The Great Tournament,15823,X360,2010.0,Sports,Tradewest,0.00,0.01,0.00,0.00,0.02
IHRA Drag Racing: Sportsman Edition,15957,XB,2006.0,Racing,Bethesda Softworks,0.01,0.00,0.00,0.00,0.02
RalliSport Challenge(JP sales),16328,XB,2002.0,Racing,Microsoft Game Studios,0.00,0.00,0.01,0.00,0.01
Original Frisbee Disc Sports: Ultimate & Golf,16567,DS,2007.0,Action,"Destination Software, Inc",0.01,0.00,0.00,0.00,0.01

In [269]:
games["Global_Sales"].mean()

0.53744065550074

In [270]:
genres = games.groupby("Genre")

In [271]:
genres["Global_Sales"].sum()

Genre
Action          1751.18
Adventure        239.04
Fighting         448.91
Misc             809.96
Platform         831.37
Puzzle           244.95
Racing           732.04
Role-Playing     927.37
Shooter         1037.37
Simulation       392.20
Sports          1330.93
Strategy         175.12
Name: Global_Sales, dtype: float64

In [272]:
genres["Global_Sales"].sum().sort_values(ascending = False)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Misc             809.96
Racing           732.04
Fighting         448.91
Simulation       392.20
Puzzle           244.95
Adventure        239.04
Strategy         175.12
Name: Global_Sales, dtype: float64

In [273]:
#Series bir boyutludur dataframe iki boyutlu

In [274]:
games.Global_Sales.head()

Name
Wii Sports                  82.74
Super Mario Bros.           40.24
Mario Kart Wii              35.82
Wii Sports Resort           33.00
Pokemon Red/Pokemon Blue    31.37
Name: Global_Sales, dtype: float64

In [275]:
games["Global_Sales"].head()

Name
Wii Sports                  82.74
Super Mario Bros.           40.24
Mario Kart Wii              35.82
Wii Sports Resort           33.00
Pokemon Red/Pokemon Blue    31.37
Name: Global_Sales, dtype: float64

In [276]:
games[["Global_Sales","Genre","Year"]].head()

                          Global_Sales         Genre    Year
Name
Wii Sports                       82.74        Sports  2006.0
Super Mario Bros.                40.24      Platform  1985.0
Mario Kart Wii                   35.82        Racing  2008.0
Wii Sports Resort                33.00        Sports  2009.0
Pokemon Red/Pokemon Blue         31.37  Role-Playing  1996.0

In [277]:
# loc komutunda satir ve sutun isimleri girilerek secme yapilir 
# iloc komutunda satir ve sutun indexlerli girilir ilk parametre satir ikinic sutun

In [278]:
games.iloc[0]

Rank                   1
Platform             Wii
Year              2006.0
Genre             Sports
Publisher       Nintendo
NA_Sales           41.49
EU_Sales           29.02
JP_Sales            3.77
Other_Sales         8.46
Global_Sales       82.74
Name: Wii Sports, dtype: object

In [279]:
games.iloc[0,2]

2006.0

In [280]:
games.iloc[0,[0,2,3]]

Rank          1
Year     2006.0
Genre    Sports
Name: Wii Sports, dtype: object

In [281]:
games.iloc[0:3,[0,2,3]] # 1. satirdan 3.satira kadar olan satirdaki 1.3.ve4. sutunlari basar

                   Rank    Year     Genre
Name
Wii Sports            1  2006.0    Sports
Super Mario Bros.     2  1985.0  Platform
Mario Kart Wii        3  2008.0    Racing

In [282]:
games.iloc[0:3,1:4]

                  Platform    Year     Genre
Name
Wii Sports             Wii  2006.0    Sports
Super Mario Bros.      NES  1985.0  Platform
Mario Kart Wii         Wii  2008.0    Racing

In [283]:
games = pd.read_csv("vgsalesGlobale.csv") # name veri setinin indexi oldu
#games = pd.read_csv("vgsalesGlobale.csv",index_col="Name") # name veri setinin indexi oldu
# boyle oldugu zaman asagidaki gibi indexleme yapamiyoruz cunku indeximiz stringe donusmus oluyor
games.loc[0:5,"Rank":"Genre"]

   Rank                      Name Platform    Year         Genre
0     1                Wii Sports      Wii  2006.0        Sports
1     2         Super Mario Bros.      NES  1985.0      Platform
2     3            Mario Kart Wii      Wii  2008.0        Racing
3     4         Wii Sports Resort      Wii  2009.0        Sports
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing
5     6                    Tetris       GB  1989.0        Puzzle

In [284]:
games.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [285]:
games.dropna(axis=0).shape

(16291, 11)

In [286]:
games.dropna(axis=1,how = "any").shape

(16598, 9)

In [287]:
games.dropna(axis="columns",how = "any").shape

(16598, 9)

In [288]:
games.dropna(axis="rows",how = "any").shape

(16291, 11)

In [290]:
games.Genre.value_counts()

Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: Genre, dtype: int64